name: Pull Request Triggered Actions
run-name: Pull Request CI - ${{ github.run_number }}_${{ github.run_attempt }}
on:
  pull_request:
    branches: [main]


jobs:
  CalculateGitTagAndRetention:
    uses: ./.github/workflows/ees.common.GitVersionAndRetentionFromConfig.yml
    secrets: inherit

  Build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    needs: CalculateGitTagAndRetention
    with:
        gitVersion: ${{needs.calculateGitTagAndRetention.outputs.GIT_TAG}}
        daysToRetain: ${{ needs.CalculateGitTagAndRetention.outputs.ARTIFACT_RETENTION_IN_DAYS }}
