name: Hello World!
on:
  push
jobs:
  demo-workflow:
    name: A sample demo workflow file
    runs-on: ubuntu-latest

    steps: 
      - name: Checking out the code
        uses: actions/checkout@v4

      - name: Greetings!
        run: echo "Hello!World!"

      - name: Checkout srinivasthoudoju repository
        uses: actions/checkout@v4
        with:
          repository: srinivasthoudoju/srinivasthoudoju
          path: "srinivasthoudoju"

      - name: List the workspace and the files
        run: |
          echo "${{github.workspace}}"
          ls $GITHUB_WORKSPACE
          ls ${{github.workspace}}/srinivasthoudoju
          
    
